# -*- coding: utf-8 -*-
"""Esterification kinetics

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YeqAH5x6uFdqtRbw0x4RkT9_PuoOFjs8
"""

import numpy as np
from scipy.integrate import odeint
import matplotlib.pyplot as plt

# the Rate Equation (A + B <-> C + D)
# A-Salicylic Acid, B-Alcohol, C-Ester, D-Water
def esterification(y, t, k_forward, k_backward, remove_water=False):
    A, B, C, D = y

    # Rate of reaction
    rate = k_forward * A * B - k_backward * C * D

    dA_dt = -rate
    dB_dt = -rate
    dC_dt = rate
    # If remove_water is True, we simulate the Dean-Stark trap (D stays near 0)
    dD_dt = 0 if remove_water else rate

    return [dA_dt, dB_dt, dC_dt, dD_dt]

#Initial Conditions (3:1 Alcohol to Acid ratio )
A0 = 1.0  # Acid
B0 = 3.0  # Alcohol (Excess) [cite: 1, 24]
C0 = 0.0  # Ester
D0 = 0.0  # Water
y0 = [A0, B0, C0, D0]

t = np.linspace(0, 10, 100) # Time scale
k_f, k_b = 0.5, 0.2         # Reaction constants

#Simulations
sol_no_removal = odeint(esterification, y0, t, args=(k_f, k_b, False))
sol_with_removal = odeint(esterification, y0, t, args=(k_f, k_b, True))

#Plotting the results
plt.figure(figsize=(10, 6))
plt.plot(t, sol_no_removal[:, 2], 'r--', label='Without Water Removal (Equilibrium Limit)')
plt.plot(t, sol_with_removal[:, 2], 'g-', label='With Continuous Water Removal (Proposed Method)')
plt.title('Kinetic Simulation: Effect of Water Removal on Tridecyl Salicylate Yield')
plt.xlabel('Time (normalized)')
plt.ylabel('Concentration of Ester (Yield)')
plt.legend()
plt.grid(True)
plt.savefig('kinetics_plot.png')
plt.show()