# -*- coding: utf-8 -*-
"""data_augmentation.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zpOa27Hho-w3mtA6W_CzEEcpfsmgXOFf
"""



import numpy as np
import pandas as pd
from sklearn.ensemble import RandomForestRegressor
import matplotlib.pyplot as plt

np.random.seed(42)
n_samples = 500

#  vary Temp (90-120C), Time (10-60h), and Molar Ratio (2-5)
temp = np.random.uniform(90, 120, n_samples)
time = np.random.uniform(10, 60, n_samples)
ratio = np.random.uniform(2, 5, n_samples)

yield_pct = 100 * (1 - np.exp(-0.0001 * (temp-60) * time * (ratio/3)))
yield_pct = np.clip(yield_pct + np.random.normal(0, 1, n_samples), 0, 99) # Add some 'real world' noise

df = pd.DataFrame({'Temperature': temp, 'Time_hours': time, 'Molar_Ratio': ratio, 'Yield_pct': yield_pct})


df.to_csv('ai_training_data.csv', index=False)