# -*- coding: utf-8 -*-
"""final optimization map.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1s__8CNCBeZyP7IPTW_VvwG0WMkrnCIAC
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.ensemble import RandomForestRegressor
from mpl_toolkits.mplot3d import Axes3D

# 1. LOAD DATA
data = pd.read_csv('ai_training_data.csv')

# 2. DEFINE FEATURES AND TRAIN MODEL
X = data[['Temperature', 'Time_hours', 'Molar_Ratio']]
y = data['Yield_pct']

model = RandomForestRegressor(n_estimators=100, random_state=42)
model.fit(X, y)

t_space = np.linspace(90, 120, 50)
h_space = np.linspace(10, 60, 50)
T, H = np.meshgrid(t_space, h_space)

Z = np.array([model.predict(pd.DataFrame([[t, h, 3]],
             columns=['Temperature', 'Time_hours', 'Molar_Ratio']))[0]
             for t, h in zip(np.ravel(T), np.ravel(H))])
Z = Z.reshape(T.shape)

# visualisation
fig = plt.figure(figsize=(12, 8))
ax = fig.add_subplot(111, projection='3d')
surf = ax.plot_surface(T, H, Z, cmap='viridis', edgecolor='none', alpha=0.9)

ax.set_title('Final Process Optimization: Tridecyl Salicylate', fontsize=16)
ax.set_xlabel('Temperature (°C)')
ax.set_ylabel('Time (hours)')
ax.set_zlabel('Predicted Yield (%)')
fig.colorbar(surf, ax=ax, shrink=0.5, aspect=10)


plt.savefig('final_optimization_map.png', dpi=300, bbox_inches='tight')
plt.show()

print("The 3D MAP")