# -*- coding: utf-8 -*-
"""ml_predictor.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OZlK9spqu5r9EQXLhzNDGCt89YNDC__J
"""

def get_prediction(temp, time, ratio):

    input_data = pd.DataFrame([[temp, time, ratio]],
                             columns=['Temperature', 'Time_hours', 'Molar_Ratio'])

    # Predict using the named DataFrame
    prediction = model.predict(input_data)[0]

    print("-" * 30)
    print(f"ML Trained Model")
    print("-" * 30)
    print(f"Conditions: {temp}°C | {time} hours | {ratio}:1 Ratio")
    print(f"Predicted Yield: {prediction:.2f}%")
    print("-" * 30)

    if prediction > 90:
        print("STATUS: Optimal Production Zone")
    elif prediction > 70:
        print("STATUS: Sub-optimal. Consider increasing Temp/Time.")
    else:
        print("STATUS: Low Yield. Inefficient process parameters.")

# final test
get_prediction(temp=108, time=50, ratio=3)