# -*- coding: utf-8 -*-
"""Heater calculations.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CUZRxaEehYI7oyojoWgsCyEDTkDFgAMC
"""

# Phase 3 - Step 2: Energy Balance & Heating Requirement
def calculate_energy_balance(total_mass_kg, delta_t=83, heating_time_hr=2):
    # Constants for Tridecyl Salicylate / Alcohol mixture
    # Specific Heat Capacity (Cp) is approx 2.1 kJ/kg*C for these organics
    cp_organic = 2.1
    # Latent heat of water vaporization (kJ/kg)
    latent_heat_water = 2260
    water_mass_kg = 5.92 # From our mass balance

    # 1. Sensible Heat (Energy to raise temperature)
    # Q = m * Cp * Delta_T
    q_sensible = total_mass_kg * cp_organic * delta_t

    # 2. Latent Heat (Energy to boil off the water byproduct)
    q_latent = water_mass_kg * latent_heat_water

    total_energy_kj = q_sensible + q_latent

    # 3. Power Requirement (kW = kJ / seconds)
    power_kw = total_energy_kj / (heating_time_hr * 3600)

    # 4. Adding a 20% safety factor for heat loss to surroundings
    required_heater_kw = power_kw * 1.2

    print(f"--- ENERGY BALANCE FOR 100kg BATCH ---")
    print(f"Total Mass to Heat: {total_mass_kg} kg")
    print(f"Temperature Rise: {delta_t} °C")
    print(f"---------------------------------------")
    print(f"Total Energy Required: {round(total_energy_kj, 2)} kJ")
    print(f"Theoretical Power: {round(power_kw, 2)} kW")
    print(f"RECOMMENDED HEATER CAPACITY: {round(required_heater_kw, 2)} kW")
    print(f"(Assuming {heating_time_hr} hour ramp-up time)")

# Total mass from our previous code was ~242kg
calculate_energy_balance(242)