# -*- coding: utf-8 -*-
"""kilo scale analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1B9olggcYH2ND6n44NzM4VbIJtv3xRqU7
"""



import pandas as pd

def process_master_calculator(target_product_kg=100, yield_pct=95, recovery_efficiency=90):
    # (Molecular Weights g/mol) ---
    MW_ACID = 138.12    # Salicylic Acid
    MW_ALCOHOL = 200.36 # Tridecyl Alcohol
    MW_ESTER = 320.48   # Tridecyl Salicylate
    MW_WATER = 18.02    # Byproduct

    #MASS BALANCE CALCULATIONS
    required_moles = (target_product_kg * 1000) / (MW_ESTER * (yield_pct / 100))

    # Reactants required based on 3:1 Molar Ratio
    mass_acid_kg = (required_moles * MW_ACID) / 1000
    mass_alcohol_total_kg = (required_moles * 3 * MW_ALCOHOL) / 1000

    # Catalyst (PTSA) usually at 0.5% of total reactor charge
    mass_catalyst_kg = (mass_acid_kg + mass_alcohol_total_kg) * 0.005

    # OUTPUT & RECOVERY CALCULATIONS
    # Only 1 mole of alcohol reacts. The rest is excess.
    alcohol_consumed_kg = (required_moles * MW_ALCOHOL) / 1000
    alcohol_excess_kg = mass_alcohol_total_kg - alcohol_consumed_kg

    # Recovery based on vacuum distillation efficiency
    alcohol_recovered_kg = alcohol_excess_kg * (recovery_efficiency / 100)

    # Water byproduct (Dean-Stark removal)
    water_produced_kg = (required_moles * MW_WATER) / 1000

    # --- 4. PRINTING THE REPORT ---
    print(f"==================================================")
    print(f"   KILO-SCALE PROCESS DESIGN REPORT ({target_product_kg}kg)")
    print(f"==================================================")
    print(f"INPUTS (The Charge Sheet):")
    print(f"  > Salicylic Acid:      {mass_acid_kg:.2f} kg")
    print(f"  > Tridecyl Alcohol:    {mass_alcohol_total_kg:.2f} kg (3:1 Excess)")
    print(f"  > PTSA Catalyst:       {mass_catalyst_kg:.2f} kg")
    print(f"--------------------------------------------------")
    print(f"OUTPUTS & RECOVERY:")
    print(f"  > Theoretical Ester:   {target_product_kg:.2f} kg ({yield_pct}% yield)")
    print(f"  > Water Byproduct:     {water_produced_kg:.2f} kg (To be removed)")
    print(f"  > Alcohol Recovered:   {alcohol_recovered_kg:.2f} kg ({recovery_efficiency}% recovery)")
    print(f"--------------------------------------------------")
    print(f"EFFICIENCY METRICS:")
    print(f"  > Atom Economy:        { (MW_ESTER / (MW_ACID + MW_ALCOHOL)) * 100 :.1f}%")
    print(f"  > Total Reactor Mass:  {mass_acid_kg + mass_alcohol_total_kg:.2f} kg")
    print(f"==================================================")

# Execute the master plan for 100kg
process_master_calculator(target_product_kg=100, yield_pct=95, recovery_efficiency=90)